all : eric bye wall siva 
bye :
	${CC} bye.c -o bye

#clean :
#	rm -rf bye
wall :
	        ${CC} wall.c -o wall
#clean :
#	rm -rf wall
siva :
	${CC} siva.c -o siva
#clean :
#	rm -rf siva
#eric :
#	${CC} eric.c -o eric
clean :
	rm -rf eric bye siva wall
