all : add subb mul div prime fabonacci

add :
	${CC} add.c -o add

subb :
	${CC} subb.c -o subb
mul :
	${CC} mul.c -o mul
div :
	${CC} div.c -o div
prime :
	${CC} prime.c -o prime
fabonacci : 
	${CC} fabonacci.c -o fab
clean :
	rm add subb mul div prime fabonacci

